### ISSUE TITLE
Download warpx.jar

### ISSUE THREAD

**Issue by SrBedrock** [ReflxctionDev/WarpsX#1]
I can't compile with intellij, would there be any way for you to make .jar available?

**Comment by Revxrsal** [comment]
> I can't compile with intellij, would there be any way for you to make .jar available?

Sorry, the problem is one of the dependencies. I'll fix it when I get home.

**Comment by SrBedrock** [comment]
[No problem, I found the spigot link.](https://www.spigotmc.org/resources/warpsx-a-powerful-feature-rich-warps-plugin.73006/)

**Comment by Revxrsal** [comment]
The dependencies should work fine now. Closing this issue
